# Base configs
baseurl: "https://christopherchangphotography.github.io"
image_fulls_loc: "/images/fulls"
image_thumbs_loc: "/images/thumbs"
google_analytics: "UA-46465113-2"

# UI configs
title: "Photography by Chris Chang"
subtitle: "See the world through my eyes!"
author: "Chris Chang"
header:
 title: "Photography"
 subtitle: "by Chris Chang"
footer:
 name: "Hello, I'm Chris"
 bio: "I study English and Biochemistry as a student in the Program of Liberal Medical Education at Brown University. Here's a glimpse into my passion for photography."
 github: "My philosophy around photography is simple: life is beautiful, but short, and I'm on a mission to record my life and experiences in a meaningful way."
web_design: "<a href=\"https://aaronjwang.com\">Aaron Wang</a>"
social_urls:
  facebook: "https://www.facebook.com/christopher.chang.18847"
  instagram: "https://www.instagram.com/c.chang23/"
  linkedin: "https://www.linkedin.com/in/christopher-chang-60a7271a0/"
  github: "https://www.github.com/christopherchangphotography"
